#!/bin/bash
PP_FILE=POP_PLACES_20140204.txt

grep \|AL\| $PP_FILE > AL.txt
grep \|AR\| $PP_FILE > AR.txt
grep \|AS\| $PP_FILE > AS.txt
grep \|AZ\| $PP_FILE > AZ.txt
grep \|CA\| $PP_FILE > CA.txt
grep \|CO\| $PP_FILE > CO.txt
grep \|CT\| $PP_FILE > CT.txt
grep \|DC\| $PP_FILE > DC.txt
grep \|DE\| $PP_FILE > DE.txt
grep \|FL\| $PP_FILE > FL.txt
grep \|FM\| $PP_FILE > FM.txt
grep \|GA\| $PP_FILE > GA.txt
grep \|GU\| $PP_FILE > GU.txt
grep \|HI\| $PP_FILE > HI.txt
grep \|IA\| $PP_FILE > IA.txt
grep \|ID\| $PP_FILE > ID.txt
grep \|IL\| $PP_FILE > IL.txt
grep \|IN\| $PP_FILE > IN.txt
grep \|KS\| $PP_FILE > KS.txt
grep \|KY\| $PP_FILE > KY.txt
grep \|LA\| $PP_FILE > LA.txt
grep \|MA\| $PP_FILE > MA.txt
grep \|MD\| $PP_FILE > MD.txt
grep \|ME\| $PP_FILE > ME.txt
grep \|MH\| $PP_FILE > MH.txt
grep \|MI\| $PP_FILE > MI.txt
grep \|MN\| $PP_FILE > MN.txt
grep \|MO\| $PP_FILE > MO.txt
grep \|MP\| $PP_FILE > MP.txt
grep \|MS\| $PP_FILE > MS.txt
grep \|MT\| $PP_FILE > MT.txt
grep \|NC\| $PP_FILE > NC.txt
grep \|ND\| $PP_FILE > ND.txt
grep \|NE\| $PP_FILE > NE.txt
grep \|NH\| $PP_FILE > NH.txt
grep \|NJ\| $PP_FILE > NJ.txt
grep \|NM\| $PP_FILE > NM.txt
grep \|NV\| $PP_FILE > NV.txt
grep \|NY\| $PP_FILE > NY.txt
grep \|OH\| $PP_FILE > OH.txt
grep \|OK\| $PP_FILE > OK.txt
grep \|OR\| $PP_FILE > OR.txt
grep \|PA\| $PP_FILE > PA.txt
grep \|PR\| $PP_FILE > PR.txt
grep \|PW\| $PP_FILE > PW.txt
grep \|RI\| $PP_FILE > RI.txt
grep \|SC\| $PP_FILE > SC.txt
grep \|SD\| $PP_FILE > SD.txt
grep \|TN\| $PP_FILE > TN.txt
grep \|TX\| $PP_FILE > TX.txt
grep \|UM\| $PP_FILE > UM.txt
grep \|UT\| $PP_FILE > UT.txt
grep \|VI\| $PP_FILE > VI.txt
grep \|VT\| $PP_FILE > VT.txt
grep \|VA\| $PP_FILE > VA.txt
grep \|WA\| $PP_FILE > WA.txt
grep \|WV\| $PP_FILE > WV.txt
grep \|WI\| $PP_FILE > WI.txt
grep \|WY\| $PP_FILE > WY.txt
